import os
import subprocess
import json
from flask import Flask, render_template, request, jsonify
from werkzeug.utils import secure_filename

app = Flask(__name__)

# Configurations
UPLOAD_FOLDER = 'uploads'
C_SOURCE_FILE = 'image_matcher.c'
C_EXECUTABLE = './image_matcher'

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def ensure_c_binary():
    """Automatically compiles the C matching engine on startup if missing."""
    if not os.path.exists(C_EXECUTABLE):
        print("[Architect] Compiling C matching engine...")
        compile_result = subprocess.run(['gcc', C_SOURCE_FILE, '-o', 'image_matcher'], capture_output=True, text=True)
        if compile_result.returncode != 0:
            print(f"[Error] C Compilation failed:\n{compile_result.stderr}")
            return False
        print("[Architect] C binary compiled successfully.")
    return True

@app.route('/')
def index():
    """Serves the frontend single-page application."""
    return render_template('index.html')

@app.route('/search', methods=['POST'])
def search_image():
    """Receives image upload, calls C backend, and returns JSON matches."""
    if 'image' not in request.files:
        return jsonify({'success': False, 'error': 'No image file provided in request.'}), 400

    file = request.files['image']
    if file.filename == '':
        return jsonify({'success': False, 'error': 'Empty filename submitted.'}), 400

    filename = secure_filename(file.filename)
    file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    file.save(file_path)

    try:
        # Ensure C binary is ready
        if not ensure_c_binary():
            return jsonify({'success': False, 'error': 'C Backend compilation error.'}), 500

        # Execute compiled C core engine, passing the saved image path as argument
        result = subprocess.run([C_EXECUTABLE, file_path], capture_output=True, text=True, timeout=5)
        
        # Clean up uploaded file after processing
        if os.path.exists(file_path):
            os.remove(file_path)

        if result.returncode != 0:
            return jsonify({'success': False, 'error': f'C engine error: {result.stderr}'}), 500

        # Parse JSON output generated by the C program
        c_output_json = json.loads(result.stdout)
        
        return jsonify({
            'success': True,
            'matches': c_output_json.get('matches', [])
        })

    except Exception as e:
        if os.path.exists(file_path):
            os.remove(file_path)
        return jsonify({'success': False, 'error': str(e)}), 500

if __name__ == '__main__':
    ensure_c_binary()
    # Run server on Replit compatible host/port configuration
    app.run(host='0.0.0.0', port=5000, debug=True)
